export interface ClientAddress {
  street: string;
  city: string;
  postalCode: string;
  country: string;
}

export interface TimelineEvent {
  id: string;
  type: "phone" | "email" | "note" | "offer" | "appointment";
  timestamp: string; // YYYY-MM-DD HH:MM
  title: string;
  content: string;
  amount?: number; // for offers
  extraTime?: string; // for appointments
  fileName?: string; // name of attached file
  fileSize?: string; // size of attached file e.g. "1.5 MB"
  fileType?: "offer" | "contract" | "invoice";
  filePath?: string; // server-returned path to the attached file, e.g. "/uploads/ev-123_doc.pdf"
  isOutgoing?: boolean;
  audioFile?: string; // path to audio recording file
  transcription?: string; // RAG or speech-to-text transcript
}

export interface Lead {
  id: string;
  name: string;             // Client name
  city: string;             // City
  clientType: "person" | "business" | "partner"; // Client type
  status: string;           // Lead state
  source: string;           // Lead source
  owner: string;            // Project manager
  value: number;            // Lead value
  createdAt: string;
  rating?: number;          // Star rating (1-5)
  
  // Extended Client Details
  phone?: string;
  email?: string;
  address?: ClientAddress;
  
  // Corporate registries (when clientType is business or partner)
  companyId?: string;
  taxId?: string;
  vatId?: string;
  contactPerson?: string;
  website?: string;
  establishmentDate?: string;
  legalForm?: string;
  skNace?: string;
  organizationSize?: string;
  ownershipType?: string;
  dataSource?: string;
  dissolutionDate?: string;
  region?: string;
  district?: string;
  
  // Interactive Timeline Logs
  timeline?: TimelineEvent[];
  
  // VAT Validation Results Cache
  vatValidationResult?: {
    valid: boolean;
    name?: string;
    address?: string;
    checkedAt?: string;
    error?: string;
  } | null;
  
  // Lead Interested Categories
  categories?: string[];

  // Lead Referral (links to another Lead/Client ID)
  referralLeadId?: string;

  // AI Summary & Verification Fingerprint
  aiSummary?: string;
  aiSummaryFingerprint?: string;
  financialSummary?: string;
}

export interface Appointment {
  id: string;
  clientName: string;
  email: string;
  date: string; // YYYY-MM-DD
  time: string; // HH:MM
  duration: number; // minutes
  status: "pending" | "confirmed" | "cancelled";
  notes: string;
  synced: boolean;
}

export interface GeneratedDocument {
  id: string;
  title: string;
  type: "proposal" | "quote" | "contract";
  clientName: string;
  value: number;
  content: string;
  createdAt: string;
  status: "draft" | "sent" | "signed" | "expired";
}

export interface MarketingChannel {
  name: string;
  spend: number;
  revenue: number;
  leadsCount: number;
}

export interface NewsletterCampaign {
  id: string;
  subject: string;
  content: string;
  segment: "all" | "leads" | "won_clients" | "employees";
  status: "draft" | "sent";
  sentAt?: string;
  stats: {
    opens: number;
    clicks: number;
    bounce: number;
    conversions: number;
  };
}

export interface Task {
  id: string;
  title: string;
  description: string;
  status: string;
  priority: "low" | "medium" | "high";
  startDate?: string; // YYYY-MM-DD
  deadline: string; // YYYY-MM-DD
  deadlineTime?: string; // HH:MM (overdue time)
  owner: string;    // Task creator or primary owner
  assignedUsers: string[]; // names of assigned team members
  relatedLeadId?: string; // linked lead or client id (optional)
  isLocking?: boolean; // if true, it blocks related lead from transitioning stages until done
  completedBy?: string; // name of user who completed the task
  completedAt?: string; // timestamp (YYYY-MM-DD HH:MM) when completed
  isAiGenerated?: boolean; // if true, task was generated by AI
}

export interface TimeLog {
  id: string;
  employeeName: string;
  projectName: string;
  clientName: string;
  hours: number;
  date: string; // YYYY-MM-DD
  description: string;
}

export interface Employee {
  id: string;
  name: string;
  role: string;
  email: string;
  avatar: string;
  performanceScore: number; // 0-100
  leaves: {
    id: string;
    startDate: string;
    endDate: string;
    type: "vacation" | "sick" | "personal";
    status: "pending" | "approved" | "rejected";
  }[];
}

export interface FormField {
  id: string;
  label: string;
  type: "text" | "email" | "tel" | "textarea" | "select";
  required: boolean;
  options?: string[]; // for select dropdowns
}

export interface CustomForm {
  id: string;
  title: string;
  description: string;
  fields: FormField[];
  createdAt: string;
  submissionsCount: number;
}

export interface FormSubmission {
  id: string;
  formId: string;
  submittedAt: string;
  data: Record<string, string>;
}

export interface UserActivityLog {
  id: string;
  action: string;
  timestamp: string;
  details?: string;
  type: "login" | "create" | "update" | "delete" | "system";
}

export interface UserProfile {
  name: string;
  email: string;
  password?: string;
  role: string;
  color: string;
  activityLog?: UserActivityLog[];
  metadata_json?: any;
}

export interface RolePermission {
  name: string;
  permissions: {
    general_config: "edit" | "view" | "nothing";
    pm_managers: "edit" | "view" | "nothing";
    pipeline_stages: "edit" | "view" | "nothing";
    traffic_sources: "edit" | "view" | "nothing";
    system_reset: "edit" | "view" | "nothing";
    [key: string]: "edit" | "view" | "nothing"; // Allow granular & custom permission slugs dynamically
  };
  defaultNavLayout?: string[]; // Array of active module item IDs in order
}

export interface UnifiedEntryRegistry {
  id: string;
  name: string;
  entryName?: string;
  folderName?: string;
  icon: string;
  color: string;
  modules: string[]; // e.g. ["title", "due_date", "file"]
  folderModules: string[]; // e.g. ["title", "due_date", "file"]
  foldersEnabled: boolean;
  showFolderSummary?: boolean;
  warningDays?: number;
  archived: boolean;
}

export interface UnifiedEntryRow {
  id: string;
  parentId: string | null;
  isFolder: boolean;
  title?: string;
  dueDate?: string;
  fileName?: string;
  fileSize?: string;
  fileType?: string;
  filePath?: string;
  clientId?: string; // Links entry/folder to a Client/Lead ID
  leadId?: string; // Links entry/folder to a Lead ID
  warningDays?: number;
  icon?: string;
}

export interface CustomDashboard {
  id: string;
  name: string;
  icon: string;
  color: string;
  prompts: { prompt: string; layout: any }[];
  layout: {
    widgets: any[];
  };
  activeModel: string;
  archived: boolean;
}

export type ProjectAttributeType = 
  | "textfield" 
  | "textarea" 
  | "select" 
  | "date" 
  | "time" 
  | "datetime" 
  | "number" 
  | "checkbox" 
  | "radio" 
  | "files"
  | "contact";

export interface ProjectAttribute {
  id: string;
  name: string;
  type: ProjectAttributeType;
  required: boolean;
  options?: string[];
}

export interface TimelineEventType {
  id: string;
  name: string;
  color: string;
  icon: string;
  attributes: ProjectAttribute[];
}

export interface ProjectType {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  attributes: ProjectAttribute[];
  hasTimeline: boolean;
  hasGantt: boolean;
  timelineEventTypes?: TimelineEventType[];
}

export interface ProjectTimelineEvent {
  id: string;
  type: string; // fallback or general categorizer
  eventType?: string; // custom event type ID
  timestamp: string; // YYYY-MM-DD HH:MM or YYYY-MM-DDTHH:MM
  title: string;
  content?: string;
  data?: Record<string, any>; // timeline event custom attributes
}

export interface ProjectGanttRow {
  id: string;
  title: string;
  contactId: string; // client id
  startDate?: string; // YYYY-MM-DD
  endDate?: string; // YYYY-MM-DD
  progress: number; // 0-100
}

export interface Project {
  id: string;
  projectTypeId: string;
  leadId?: string | null;
  clientId?: string | null;
  status: string; // e.g. "active" | "completed" | "on_hold" | "cancelled"
  managers: string[]; // employee ids or names
  data: Record<string, any>; // keyed by attribute.id
  timeline?: ProjectTimelineEvent[];
  gantt?: ProjectGanttRow[];
}


